baseURL = "http://theminja.com/"
languageCode = "en-us"
title = "The Minja"
theme = "ananke"


MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The Minja - A rock climbing, coming of age, story"
  facebook = ""
  twitter = "https://twitter.com/thminja"
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/TheMinjaTheme.jpg"
  recent_posts_number = 2